name: js
version: 0.6.0-beta.8
authors:
- Dart Team <misc@dartlang.org>
description: Access JavaScript from Dart.
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/js
environment:
  sdk: '>=1.13.0-dev.7.7 <2.0.0'
dev_dependencies:
  browser: '^0.10.0+2'
